### ISSUE TITLE
Is  `Touch() bool` really needed?

### ISSUE THREAD

**Issue by lintianzhi** [hjr265/redsync.go#12]
Why caller should call `Touch()`  ?  What if `Touch()` is hidden by `Lock()` 

In `Lock()`: run a  goruntine  to call `Touch()` regularly. Then caller can only focus on `Lock()` and `Unlock()`

**Comment by hjr265** [comment]
@lintianzhi Yes. 

Let's say due to some network issue, `Touch()` failed to reacquire the lock. In that case, with automatic touch, there is no way for the user of the lock to know if the lock they have is still valid.

**Comment by lintianzhi** [comment]
use `func (m *Mutex) TouchError() chan error` instead of `func (m *Mutex) Touch() bool` ?

**Comment by hjr265** [comment]
Maybe we can have a both. `Touch() error` and `TouchAuto() chan error`.

I am in the process of rewriting this package here: https://github.com/redsync/redsync/tree/develop . And I will take this into account.

**Comment by lintianzhi** [comment]
:+1:
