### ISSUE TITLE
Simple example fails with "failed to acquire lock"

### ISSUE THREAD

**Issue by rjammala** [hjr265/redsync.go#16]
This simple example fails with "failed to acquire lock"

I am using go tip:
go version devel +811b785 Wed Feb 10 14:42:30 2016 +0000 linux/amd64
package main

import (
	"log"
	"net"

	"github.com/hjr265/redsync.go/redsync"
)

func main() {
	m, err := redsync.NewMutex("foo", []net.Addr{&net.TCPAddr{IP: net.IPv4(127, 0, 0, 1), Port: 6379}})
	if err != nil {
		log.Fatal(err)
	}
	err = m.Lock()
	if err != nil {
		log.Fatal(err)
	}
	m.Unlock()

}

**Comment by hjr265** [comment]
Hi @rjammala .. Can you please share a bit more details? I am assuming that Redis is running properly and is accessible at port 6379 on localhost.

**Comment by rjammala** [comment]
@hjr265 : Looks like a problem with my Redis setup. It works now. Sorry for the trouble.
