### ISSUE TITLE
Redsync for a shared resource across a distributed system

### ISSUE THREAD

**Issue by csesmita** [hjr265/redsync.go#8]
Dear Authors,

Thanks for your effort in implementing the redsync algorithm in go. I am trying to use your implementation in a distributed system where multiple nodes might request for the same named resource. In that case, though the mutexes created for the same named resource are different, the lock should still succeed for one and only one node. 

The delScript inside Lock() prevents this from happening. I am trying to understand why you would need that in the first place?

(
I'd like to simulate the following behaviour at the redis-server:

127.0.0.1:6379> get uuid1
(nil)
127.0.0.1:6379> set uuid1 2345 NX PX 200000
OK
127.0.0.1:6379> get uuid1
"2345"
127.0.0.1:6379> set uuid1 1234 NX PX 200000
(nil)
127.0.0.1:6379> get uuid1
"2345"

A get fetching a non-nil value should suffice, the value needn't be equal
)

Thanks,
Smita

**Comment by hjr265** [comment]
Hi @csesmita 

(Assuming I have understood your question correctly)

This library implements the algorithm described in http://redis.io/topics/distlock . On that page, you will notice, under the "The Redlock algorithm" section, there is a step that reads:

> If the client failed to acquire the lock for some reason (either it was not able to lock N/2+1 instances or the validity time is negative), it will try to unlock all the instances (even the instances it believed it was not able to lock).

I think that is what you are talking about. The delScript essentially releases all the lock instances if it fails to acquire enough lock instances.

Hope that helps,
Ridwan

**Comment by csesmita** [comment]
Hi Ridwan,

Thank you for your response. So, just to elaborate on my design:

1. There is a shared resource which is lock protected. The distlock algorithm is used to achieve this shared lock.

2. The node that grabs the lock will run a for loop that will exit only when no more work is pending for the resource. For example: process all outstanding events for this resource. The holder of the lock should try to process as much as it can for that resource.

In this case, the requirement is to have:
1. A touch function for the dist lock which can be invoked at the end of every event processed inside the for loop. This touch function will reset the timeout at redis for the same shared resource and mutex value.
2. A get/check function that checks if the mutex value != "". Currently, the only place this is done is inside Unlock() which will go ahead and unlock if the condition is true. However, the system requirement is to check if a lock is still being held by the processing node, and if so, only then do some DB update and unlock. Else, nothing needs to be done.

These are over and beyond the functions currently defined. What do you think of these extension requests?

**Comment by csesmita** [comment]
Also, the default parameters should be made configurable as well. This is because the benchmark figures in our system really depend on the values of these default parameters.
const (
		// DefaultExpiry is used when Mutex Duration is 0
		DefaultExpiry = 8 * time.Second
		// DefaultTries is used when Mutex Duration is 0
		DefaultTries = 16
		// DefaultDelay is used when Mutex Delay is 0
		DefaultDelay = 512 * time.Millisecond
		// DefaultFactor is used when Mutex Factor is 0
		DefaultFactor = 0.01
	)

For example: changing the default expiry to 2 seconds gave us a proportional 4X faster execution times. Can these be therefore, made configurable?

**Comment by hjr265** [comment]
Hi @csesmita 

Regarding the first requirement, I think we can implement a touch function. The actual algorithm defined here (http://redis.io/topics/distlock) has a section at the end that describes the proper behavior of such a lock extension function. 

About the second one, I do not think it is safe to rely on m.value to determine if the lock is being help. This should be done elsewhere, by the user of the package. You will notice that the redsync Mutex is implemented in a way very similar to Go's standard library sync Mutex. 

And finally, about the default values. You can always override them when making the Mutex. The Mutex struct actually has exported fields for all these parameters. You can set them to whatever you want. Only setting them to their zero values will make them use the default constants.

I will reopen the issue and try to implement the touch function soon.

**Comment by csesmita** [comment]
Thanks for your response Ridwan. Yes, having a touch function will help. Also, sorry on having overlooked the default values, they are easily configurable. 

For the second issue, is it possible then to return the status of the delScript from Unlock()? An m.value match returns true, while a mismatch returns false, indicating the unlock for this mutex did not go through. Based on this value, the application can take necessary action.

Smita
